// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: db_model.proto

package pbm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Servers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           int32                  `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`          // 서버 정보 아이디
	AppId         string                 `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`       // 앱 아이디 com.dofiang.episode01~05
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`           // 서버 주소
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`     // 지역
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`        // 정렬
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"` // 생성일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Servers) Reset() {
	*x = Servers{}
	mi := &file_db_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Servers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Servers) ProtoMessage() {}

func (x *Servers) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Servers.ProtoReflect.Descriptor instead.
func (*Servers) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{0}
}

func (x *Servers) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *Servers) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Servers) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Servers) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Servers) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Servers) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type Users struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                      // 유저 인덱스 아이디
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                   // 유저 이메일
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`             // 유저 닉네임
	Image          string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`                   // 유저 프로필 이미지
	Account        string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`               // 유저 계좌
	IsSubscribe    string                 `protobuf:"bytes,6,opt,name=isSubscribe,proto3" json:"isSubscribe,omitempty"`       // 구독 여부
	SubscribeAt    string                 `protobuf:"bytes,7,opt,name=subscribeAt,proto3" json:"subscribeAt,omitempty"`       // 구독 시작
	SubscribeEndAt string                 `protobuf:"bytes,8,opt,name=subscribeEndAt,proto3" json:"subscribeEndAt,omitempty"` // 구독 종료
	LoginAt        string                 `protobuf:"bytes,9,opt,name=loginAt,proto3" json:"loginAt,omitempty"`               // 최근 접속일
	CreateAt       string                 `protobuf:"bytes,10,opt,name=createAt,proto3" json:"createAt,omitempty"`            // 생성일
	ModifyAt       string                 `protobuf:"bytes,11,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"`            // 수정일
	DeleteAt       string                 `protobuf:"bytes,12,opt,name=deleteAt,proto3" json:"deleteAt,omitempty"`            // 삭제일
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_db_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{1}
}

func (x *Users) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Users) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Users) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Users) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Users) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Users) GetIsSubscribe() string {
	if x != nil {
		return x.IsSubscribe
	}
	return ""
}

func (x *Users) GetSubscribeAt() string {
	if x != nil {
		return x.SubscribeAt
	}
	return ""
}

func (x *Users) GetSubscribeEndAt() string {
	if x != nil {
		return x.SubscribeEndAt
	}
	return ""
}

func (x *Users) GetLoginAt() string {
	if x != nil {
		return x.LoginAt
	}
	return ""
}

func (x *Users) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Users) GetModifyAt() string {
	if x != nil {
		return x.ModifyAt
	}
	return ""
}

func (x *Users) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

type BalanceMasters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bmid          int32                  `protobuf:"varint,1,opt,name=bmid,proto3" json:"bmid,omitempty"`              // 잔고 마스터 아이디
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                // 유저아이디
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`         // 계좌
	TotalMoney    float32                `protobuf:"fixed32,4,opt,name=totalMoney,proto3" json:"totalMoney,omitempty"` // 금액
	CreateAt      string                 `protobuf:"bytes,5,opt,name=createAt,proto3" json:"createAt,omitempty"`       // 생성일
	ModifyAt      string                 `protobuf:"bytes,6,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"`       // 수정일
	DeleteAt      string                 `protobuf:"bytes,7,opt,name=deleteAt,proto3" json:"deleteAt,omitempty"`       // 삭제일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceMasters) Reset() {
	*x = BalanceMasters{}
	mi := &file_db_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceMasters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceMasters) ProtoMessage() {}

func (x *BalanceMasters) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceMasters.ProtoReflect.Descriptor instead.
func (*BalanceMasters) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{2}
}

func (x *BalanceMasters) GetBmid() int32 {
	if x != nil {
		return x.Bmid
	}
	return 0
}

func (x *BalanceMasters) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *BalanceMasters) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BalanceMasters) GetTotalMoney() float32 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *BalanceMasters) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *BalanceMasters) GetModifyAt() string {
	if x != nil {
		return x.ModifyAt
	}
	return ""
}

func (x *BalanceMasters) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

type BalanceDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bdid          int32                  `protobuf:"varint,1,opt,name=bdid,proto3" json:"bdid,omitempty"`        // 잔고 상세 아이디
	Bmid          int32                  `protobuf:"varint,2,opt,name=bmid,proto3" json:"bmid,omitempty"`        // 잔고 마스터 아이디
	Money         float32                `protobuf:"fixed32,4,opt,name=money,proto3" json:"money,omitempty"`     // + - 금액
	CreateAt      string                 `protobuf:"bytes,5,opt,name=createAt,proto3" json:"createAt,omitempty"` // 생성일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceDetails) Reset() {
	*x = BalanceDetails{}
	mi := &file_db_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDetails) ProtoMessage() {}

func (x *BalanceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDetails.ProtoReflect.Descriptor instead.
func (*BalanceDetails) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceDetails) GetBdid() int32 {
	if x != nil {
		return x.Bdid
	}
	return 0
}

func (x *BalanceDetails) GetBmid() int32 {
	if x != nil {
		return x.Bmid
	}
	return 0
}

func (x *BalanceDetails) GetMoney() float32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *BalanceDetails) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type Favorities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           int32                  `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`                // 관심 카드 아이디
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                // 관심 카드 유저 아이디
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`           // 관심 카드 코드
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`       // 관심 카드 거래소 코드
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`               // 관심 카드 이름
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`           // 관심 선택당시 카드 금액
	Change        float32                `protobuf:"fixed32,7,opt,name=change,proto3" json:"change,omitempty"`         // 관심 변화
	ChangeRate    float32                `protobuf:"fixed32,8,opt,name=changeRate,proto3" json:"changeRate,omitempty"` // 관심 변화율
	CreateAt      string                 `protobuf:"bytes,9,opt,name=createAt,proto3" json:"createAt,omitempty"`       // 관심 적용일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Favorities) Reset() {
	*x = Favorities{}
	mi := &file_db_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Favorities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorities) ProtoMessage() {}

func (x *Favorities) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorities.ProtoReflect.Descriptor instead.
func (*Favorities) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{4}
}

func (x *Favorities) GetFid() int32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *Favorities) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Favorities) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Favorities) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Favorities) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Favorities) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Favorities) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Favorities) GetChangeRate() float32 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

func (x *Favorities) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type Purchases struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`            // 구매 아이디
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`            // 구매 유저 아이디
	ProductId     string                 `protobuf:"bytes,3,opt,name=productId,proto3" json:"productId,omitempty"` // 구매 상품 코드 S30, S45, S60, S120, C1000...
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`       // 구매 금액
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"`   // 구매 일자
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Purchases) Reset() {
	*x = Purchases{}
	mi := &file_db_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchases) ProtoMessage() {}

func (x *Purchases) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchases.ProtoReflect.Descriptor instead.
func (*Purchases) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{5}
}

func (x *Purchases) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Purchases) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Purchases) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Purchases) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Purchases) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type DeckMasters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dmid          int32                  `protobuf:"varint,1,opt,name=dmid,proto3" json:"dmid,omitempty"`        // 덱 마스터 아이디
	Uid           int32                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`          // 덱 유저 아이디
	AppId         string                 `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`       // 앱 아이디 com.dofiang.episode01~05
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         // 덱 이름
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"` // 덱 생성일
	ModifyAt      string                 `protobuf:"bytes,7,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"` // 덱 수정일
	DeleteAt      string                 `protobuf:"bytes,8,opt,name=deleteAt,proto3" json:"deleteAt,omitempty"` // 덱 삭제일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckMasters) Reset() {
	*x = DeckMasters{}
	mi := &file_db_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckMasters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckMasters) ProtoMessage() {}

func (x *DeckMasters) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckMasters.ProtoReflect.Descriptor instead.
func (*DeckMasters) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{6}
}

func (x *DeckMasters) GetDmid() int32 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *DeckMasters) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DeckMasters) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeckMasters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeckMasters) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *DeckMasters) GetModifyAt() string {
	if x != nil {
		return x.ModifyAt
	}
	return ""
}

func (x *DeckMasters) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

type DeckDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ddid          int32                  `protobuf:"varint,1,opt,name=ddid,proto3" json:"ddid,omitempty"`              // 덱 상세 아이디
	Dmid          int32                  `protobuf:"varint,2,opt,name=dmid,proto3" json:"dmid,omitempty"`              // 덱 마스터 아이디
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`           // 덱 카드 코드
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`       // 덱 카드 거래소 코드
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`               // 덱 카드 이름
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`           // 덱 선택당시 카드 금액
	Change        float32                `protobuf:"fixed32,7,opt,name=change,proto3" json:"change,omitempty"`         // 덱 변화
	ChangeRate    float32                `protobuf:"fixed32,8,opt,name=changeRate,proto3" json:"changeRate,omitempty"` // 덱 변화율
	CreateAt      string                 `protobuf:"bytes,9,opt,name=createAt,proto3" json:"createAt,omitempty"`       // 덱 적용일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckDetails) Reset() {
	*x = DeckDetails{}
	mi := &file_db_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckDetails) ProtoMessage() {}

func (x *DeckDetails) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckDetails.ProtoReflect.Descriptor instead.
func (*DeckDetails) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{7}
}

func (x *DeckDetails) GetDdid() int32 {
	if x != nil {
		return x.Ddid
	}
	return 0
}

func (x *DeckDetails) GetDmid() int32 {
	if x != nil {
		return x.Dmid
	}
	return 0
}

func (x *DeckDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DeckDetails) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *DeckDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeckDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DeckDetails) GetChange() float32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *DeckDetails) GetChangeRate() float32 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

func (x *DeckDetails) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type GameRecordMasters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grmid         int32                  `protobuf:"varint,1,opt,name=grmid,proto3" json:"grmid,omitempty"`      // 게임 레코드 마스터 아이디
	Grtype        string                 `protobuf:"bytes,2,opt,name=grtype,proto3" json:"grtype,omitempty"`     // 게임 룸 타입 싱글/멀티 S, M
	Rid           string                 `protobuf:"bytes,3,opt,name=rid,proto3" json:"rid,omitempty"`           // 게임 룸 아이디
	AppId         string                 `protobuf:"bytes,4,opt,name=appId,proto3" json:"appId,omitempty"`       // 앱 아이디 com.dofiang.episode01~05
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"` // 생성일
	ModifyAt      string                 `protobuf:"bytes,7,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"` // 수정일
	DeleteAt      string                 `protobuf:"bytes,8,opt,name=deleteAt,proto3" json:"deleteAt,omitempty"` // 삭제일
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRecordMasters) Reset() {
	*x = GameRecordMasters{}
	mi := &file_db_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRecordMasters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRecordMasters) ProtoMessage() {}

func (x *GameRecordMasters) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRecordMasters.ProtoReflect.Descriptor instead.
func (*GameRecordMasters) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{8}
}

func (x *GameRecordMasters) GetGrmid() int32 {
	if x != nil {
		return x.Grmid
	}
	return 0
}

func (x *GameRecordMasters) GetGrtype() string {
	if x != nil {
		return x.Grtype
	}
	return ""
}

func (x *GameRecordMasters) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *GameRecordMasters) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameRecordMasters) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *GameRecordMasters) GetModifyAt() string {
	if x != nil {
		return x.ModifyAt
	}
	return ""
}

func (x *GameRecordMasters) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

type GameRecordDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grdid         int32                  `protobuf:"varint,1,opt,name=grdid,proto3" json:"grdid,omitempty"`  // 게임 레코드 상세 아이디
	Grmid         int32                  `protobuf:"varint,2,opt,name=grmid,proto3" json:"grmid,omitempty"`  // 게임 레코드 마스터 아이디
	Uid           int32                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`      // 게임 유저 아이디
	Record        string                 `protobuf:"bytes,4,opt,name=record,proto3" json:"record,omitempty"` // W, F, D
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRecordDetails) Reset() {
	*x = GameRecordDetails{}
	mi := &file_db_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRecordDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRecordDetails) ProtoMessage() {}

func (x *GameRecordDetails) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRecordDetails.ProtoReflect.Descriptor instead.
func (*GameRecordDetails) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{9}
}

func (x *GameRecordDetails) GetGrdid() int32 {
	if x != nil {
		return x.Grdid
	}
	return 0
}

func (x *GameRecordDetails) GetGrmid() int32 {
	if x != nil {
		return x.Grmid
	}
	return 0
}

func (x *GameRecordDetails) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GameRecordDetails) GetRecord() string {
	if x != nil {
		return x.Record
	}
	return ""
}

type PokerGameMasters struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Pkgmid            int32                  `protobuf:"varint,1,opt,name=pkgmid,proto3" json:"pkgmid,omitempty"`                        // 포커 게임 마스터 아이디
	Grmid             int32                  `protobuf:"varint,2,opt,name=grmid,proto3" json:"grmid,omitempty"`                          // 게임 레코드 마스터 아이디
	TotalBettingPrice float32                `protobuf:"fixed32,3,opt,name=totalBettingPrice,proto3" json:"totalBettingPrice,omitempty"` // 총 배팅 금액
	CreateAt          string                 `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`                     // 생성일
	ModifyAt          string                 `protobuf:"bytes,5,opt,name=modifyAt,proto3" json:"modifyAt,omitempty"`                     // 수정일
	DeleteAt          string                 `protobuf:"bytes,6,opt,name=deleteAt,proto3" json:"deleteAt,omitempty"`                     // 삭제일
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PokerGameMasters) Reset() {
	*x = PokerGameMasters{}
	mi := &file_db_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokerGameMasters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokerGameMasters) ProtoMessage() {}

func (x *PokerGameMasters) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokerGameMasters.ProtoReflect.Descriptor instead.
func (*PokerGameMasters) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{10}
}

func (x *PokerGameMasters) GetPkgmid() int32 {
	if x != nil {
		return x.Pkgmid
	}
	return 0
}

func (x *PokerGameMasters) GetGrmid() int32 {
	if x != nil {
		return x.Grmid
	}
	return 0
}

func (x *PokerGameMasters) GetTotalBettingPrice() float32 {
	if x != nil {
		return x.TotalBettingPrice
	}
	return 0
}

func (x *PokerGameMasters) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *PokerGameMasters) GetModifyAt() string {
	if x != nil {
		return x.ModifyAt
	}
	return ""
}

func (x *PokerGameMasters) GetDeleteAt() string {
	if x != nil {
		return x.DeleteAt
	}
	return ""
}

type PokerGameDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pkgdbid       int32                  `protobuf:"varint,1,opt,name=pkgdbid,proto3" json:"pkgdbid,omitempty"`            // 포커게임 상세 아이디
	Pkgmid        int32                  `protobuf:"varint,2,opt,name=pkgmid,proto3" json:"pkgmid,omitempty"`              // 포커게임 마스터 아이디
	Uid           int32                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`                    // 유저아이디
	BettingPrice  float32                `protobuf:"fixed32,4,opt,name=bettingPrice,proto3" json:"bettingPrice,omitempty"` // 유저 배팅금액
	RewardPrice   float32                `protobuf:"fixed32,6,opt,name=rewardPrice,proto3" json:"rewardPrice,omitempty"`   // 보상 금액
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokerGameDetails) Reset() {
	*x = PokerGameDetails{}
	mi := &file_db_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokerGameDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokerGameDetails) ProtoMessage() {}

func (x *PokerGameDetails) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokerGameDetails.ProtoReflect.Descriptor instead.
func (*PokerGameDetails) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{11}
}

func (x *PokerGameDetails) GetPkgdbid() int32 {
	if x != nil {
		return x.Pkgdbid
	}
	return 0
}

func (x *PokerGameDetails) GetPkgmid() int32 {
	if x != nil {
		return x.Pkgmid
	}
	return 0
}

func (x *PokerGameDetails) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PokerGameDetails) GetBettingPrice() float32 {
	if x != nil {
		return x.BettingPrice
	}
	return 0
}

func (x *PokerGameDetails) GetRewardPrice() float32 {
	if x != nil {
		return x.RewardPrice
	}
	return 0
}

type Ratios struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int32                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Ratio         string                 `protobuf:"bytes,2,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CreateAt      string                 `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ratios) Reset() {
	*x = Ratios{}
	mi := &file_db_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ratios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ratios) ProtoMessage() {}

func (x *Ratios) ProtoReflect() protoreflect.Message {
	mi := &file_db_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ratios.ProtoReflect.Descriptor instead.
func (*Ratios) Descriptor() ([]byte, []int) {
	return file_db_model_proto_rawDescGZIP(), []int{12}
}

func (x *Ratios) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *Ratios) GetRatio() string {
	if x != nil {
		return x.Ratio
	}
	return ""
}

func (x *Ratios) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Ratios) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

var File_db_model_proto protoreflect.FileDescriptor

var file_db_model_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x64, 0x62, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8b, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0xd5,
	0x02, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x69, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x6e, 0x64,
	0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x22, 0xc4, 0x01, 0x0a, 0x0e, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6d, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x22, 0x6a, 0x0a,
	0x0e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62,
	0x64, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x62, 0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0xe2, 0x01, 0x0a, 0x0a, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x66, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x7f,
	0x0a, 0x09, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22,
	0xb1, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64,
	0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x64, 0x64, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x6d, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0xbd, 0x01,
	0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x6d, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x22, 0x69, 0x0a,
	0x11, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x67, 0x72, 0x64, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6d, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x6d, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0xc2, 0x01, 0x0a, 0x10, 0x50, 0x6f, 0x6b,
	0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6b, 0x67, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x6b, 0x67, 0x6d, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6d, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x6d, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x74, 0x22, 0x9c, 0x01,
	0x0a, 0x10, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6b, 0x67, 0x64, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6b, 0x67, 0x64, 0x62, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6b, 0x67, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6b,
	0x67, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x62, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x64, 0x0a, 0x06,
	0x52, 0x61, 0x74, 0x69, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x42, 0x0f, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x6d, 0xaa, 0x02, 0x03,
	0x50, 0x62, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_db_model_proto_rawDescOnce sync.Once
	file_db_model_proto_rawDescData []byte
)

func file_db_model_proto_rawDescGZIP() []byte {
	file_db_model_proto_rawDescOnce.Do(func() {
		file_db_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_model_proto_rawDesc), len(file_db_model_proto_rawDesc)))
	})
	return file_db_model_proto_rawDescData
}

var file_db_model_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_db_model_proto_goTypes = []any{
	(*Servers)(nil),           // 0: Servers
	(*Users)(nil),             // 1: Users
	(*BalanceMasters)(nil),    // 2: BalanceMasters
	(*BalanceDetails)(nil),    // 3: BalanceDetails
	(*Favorities)(nil),        // 4: Favorities
	(*Purchases)(nil),         // 5: Purchases
	(*DeckMasters)(nil),       // 6: DeckMasters
	(*DeckDetails)(nil),       // 7: DeckDetails
	(*GameRecordMasters)(nil), // 8: GameRecordMasters
	(*GameRecordDetails)(nil), // 9: GameRecordDetails
	(*PokerGameMasters)(nil),  // 10: PokerGameMasters
	(*PokerGameDetails)(nil),  // 11: PokerGameDetails
	(*Ratios)(nil),            // 12: Ratios
}
var file_db_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_model_proto_init() }
func file_db_model_proto_init() {
	if File_db_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_model_proto_rawDesc), len(file_db_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_model_proto_goTypes,
		DependencyIndexes: file_db_model_proto_depIdxs,
		MessageInfos:      file_db_model_proto_msgTypes,
	}.Build()
	File_db_model_proto = out.File
	file_db_model_proto_goTypes = nil
	file_db_model_proto_depIdxs = nil
}
