// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: db_snapshot.proto

package pbm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slid          int32                  `protobuf:"varint,1,opt,name=slid,proto3" json:"slid,omitempty"`
	Snapshot      string                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CreateAt      string                 `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotLogs) Reset() {
	*x = SnapshotLogs{}
	mi := &file_db_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotLogs) ProtoMessage() {}

func (x *SnapshotLogs) ProtoReflect() protoreflect.Message {
	mi := &file_db_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotLogs.ProtoReflect.Descriptor instead.
func (*SnapshotLogs) Descriptor() ([]byte, []int) {
	return file_db_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotLogs) GetSlid() int32 {
	if x != nil {
		return x.Slid
	}
	return 0
}

func (x *SnapshotLogs) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *SnapshotLogs) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SnapshotLogs) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             string                 `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`       // 종목명
	Ne            string                 `protobuf:"bytes,2,opt,name=ne,proto3" json:"ne,omitempty"`     // 종목명영문
	S             string                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`       // 심볼(종목코드드)
	E             string                 `protobuf:"bytes,4,opt,name=e,proto3" json:"e,omitempty"`       // 거래소 ex(KOSPI, KOSDAQ, NYSE, NASDAQ)
	C             float64                `protobuf:"fixed64,5,opt,name=c,proto3" json:"c,omitempty"`     // 등락차이
	Cr            float64                `protobuf:"fixed64,6,opt,name=cr,proto3" json:"cr,omitempty"`   // 등락률
	Pcp           float64                `protobuf:"fixed64,7,opt,name=pcp,proto3" json:"pcp,omitempty"` // 전일자종가
	Cp            float64                `protobuf:"fixed64,8,opt,name=cp,proto3" json:"cp,omitempty"`   // 현재가(현재종가)
	Op            float64                `protobuf:"fixed64,9,opt,name=op,proto3" json:"op,omitempty"`   // 시가
	Hp            float64                `protobuf:"fixed64,10,opt,name=hp,proto3" json:"hp,omitempty"`  // 고가
	Lp            float64                `protobuf:"fixed64,11,opt,name=lp,proto3" json:"lp,omitempty"`  // 저가가
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_db_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_db_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_db_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Snapshot) GetNe() string {
	if x != nil {
		return x.Ne
	}
	return ""
}

func (x *Snapshot) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Snapshot) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *Snapshot) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Snapshot) GetCr() float64 {
	if x != nil {
		return x.Cr
	}
	return 0
}

func (x *Snapshot) GetPcp() float64 {
	if x != nil {
		return x.Pcp
	}
	return 0
}

func (x *Snapshot) GetCp() float64 {
	if x != nil {
		return x.Cp
	}
	return 0
}

func (x *Snapshot) GetOp() float64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Snapshot) GetHp() float64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Snapshot) GetLp() float64 {
	if x != nil {
		return x.Lp
	}
	return 0
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`   // subscribe, unsubscribe
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`   // KRX (한국주식), SEC (미국주식)
	Symbols       []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"` // 심볼(종목코드드)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_db_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_db_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_db_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *Stream) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Stream) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Stream) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_db_snapshot_proto protoreflect.FileDescriptor

var file_db_snapshot_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x64, 0x62, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x0c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4c,
	0x6f, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x6c, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6e, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73,
	0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x63, 0x12, 0x0e, 0x0a, 0x02,
	0x63, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x63, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x63, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x70, 0x63, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x63, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x63, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x68, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x68, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x6c, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x6c, 0x70, 0x22, 0x52,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x73, 0x42, 0x0f, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x6d, 0xaa, 0x02, 0x03,
	0x50, 0x62, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_db_snapshot_proto_rawDescOnce sync.Once
	file_db_snapshot_proto_rawDescData []byte
)

func file_db_snapshot_proto_rawDescGZIP() []byte {
	file_db_snapshot_proto_rawDescOnce.Do(func() {
		file_db_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_snapshot_proto_rawDesc), len(file_db_snapshot_proto_rawDesc)))
	})
	return file_db_snapshot_proto_rawDescData
}

var file_db_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_db_snapshot_proto_goTypes = []any{
	(*SnapshotLogs)(nil), // 0: SnapshotLogs
	(*Snapshot)(nil),     // 1: Snapshot
	(*Stream)(nil),       // 2: Stream
}
var file_db_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_snapshot_proto_init() }
func file_db_snapshot_proto_init() {
	if File_db_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_snapshot_proto_rawDesc), len(file_db_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_snapshot_proto_goTypes,
		DependencyIndexes: file_db_snapshot_proto_depIdxs,
		MessageInfos:      file_db_snapshot_proto_msgTypes,
	}.Build()
	File_db_snapshot_proto = out.File
	file_db_snapshot_proto_goTypes = nil
	file_db_snapshot_proto_depIdxs = nil
}
