version: "3"
services:
  postgres:
    image: postgres:15.7-alpine3.20
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: *****
      POSTGRES_PASSWORD: *****
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5-alpine
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379 --requirepass ******
    volumes:
      - ./data/redis/:/var/lib/redis/data
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
